
services:
  postgres:
    image: postgres:16
    container_name: kuntur_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: kuntur
      POSTGRES_PASSWORD: kuntur
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kuntur"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kuntur_network

  keycloak:
    platform: linux/amd64
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: kuntur
      KC_DB_PASSWORD: kuntur
      KC_LOG_LEVEL: info
    volumes:
      - ./config/keycloak/kuntur.json:/opt/keycloak/data/import/kuntur.json
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kuntur_network

volumes:
  postgres_data:

networks:
  kuntur_network:
    driver: bridge