build:
	dotnet build Kuntur.API.sln

run:
	dotnet run --project src/Kuntur.API.Host/Kuntur.API.Host.csproj

up:
	docker-compose -f docker-compose.yml up -d --build

down:
	docker-compose -f docker-compose.yml down --remove-orphans

